name: CI for FlexOrder Plugin

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:
    branches: [ main, dev, qa ]
  # Triggers the workflow on push events
  push:
    branches: [ main, dev, qa ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Run-e2e-TestCase:
    name: Run FlexOrder Features Test Cases
    runs-on: ubuntu-latest
    env: 
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ./

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Check current directory and listings
      - name: Current directory and listings
        run: |
          pwd
          ls -al

      # Install and config site using Docker
      - name: Install and config site
        uses: docker://rtcamp/base-wo:v1.0.0
        env:
          NODE_VERSION: 18
          GITHUB_WORKSPACE: ${{ github.workspace }}

      # Make setup script executable and run it
      - name: Setup WordPress and run tests
        run: |
          chmod +x scripts/setup-wordpress-site.sh
          ./scripts/setup-wordpress-site.sh

      # Archive HTML Report on failure
      - name: Archive HTML Report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report

      # Archive screenshots on failure
      - name: Archive screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: |
            test-results/**/*.png
            *.png

      # Cleanup
      - name: Cleanup
        if: ${{ always() }}
        uses: rtCamp/action-cleanup@master 